language: rust
cache: cargo
rust:
  - nightly
os: 
  - linux

deploy:
  provider: releases
  api_key:
    secure: yTQFQ4/G0QIXx0BD4y/Ovvb1+IJxsTS0R52uCOhKaoZxG+UYPxh5FJJkhalbNzEdSTiT76zk0jtydRuSb0IfQ9QtmX/6e5YTOzRDMBHppe1j6CTred1dZJMrh2qkbaTt2Ks2DqhHDAEOUFwCobB6fA6+vggvgCYxD/cK8v5BuAUzbPOqefHABKXdHUayx0CAJHUE9HtBDLKYLR75hJ2m59LqJo/DWb5nW/uyZSrxlUS8O5HReEigUgG7MzjSVcdWc/nB+rDsXOV9zcsW6/lAiRd3mnWefu0F6q/ffuWFsA2fKDzSNrrDdRdOi5zf6vAwkfg39GMxad99FkoH26hIFAWyee52K5uYKOjhsK9MMWe4lqExkYNVqZvaGvdue8+ODQf1ekQWd6sFNM/nlq5Wn6U3jeyrwaa1GqJ3TZdCecGkSlK1Vfqg7ZaxCSvh4Q90iog8K9y6Ne6PG/6XpOi5A/L+j/BX5nC0A4MecqBzzbBn9Kt5px2wo8a7MX+olyrh7mlo5uhhlcxwZ4D68ao4tYFkiWevLpjs4C2mXXAQpAw1VsFPfEvlVOByYJ2GSb6fZC7vtudNQLsyfDduM0tsu/hKdW7qpthRY+2sSdSEvyua3Wcy1SyLqz4yVwR5i2PyC8RN9GDiuHP5O5fVywFicxt7yrDKaMOqz/7H/AP9L9c=
  file: net_hex
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: JackNewman12/NetHex
