[package]
name = "net_hex"
version = "0.1.0"
authors = ["jack"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.pnet]
version = "0.22.0"