[package]
name = "net_hex"
version = "0.1.0"
authors = ["jack"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexplay = "*"
hex = "0.3.2"
clap = "2.33.0"

[dependencies.pnet]
version = "0.22.0"

[profile.release]
lto = true