[package]
name = "net_hex"
version = "0.3.0"
authors = ["Jack Newman jacknewman12@gmail.com"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexplay = "*"
hex = "0.3.2"
structopt = "0.2"

[dependencies.pnet]
version = "0.22.0"

[profile.release]
lto = true