[package]
name = "net_hex"
version = "0.6.1-alpha.0"
authors = ["Jack Newman jacknewman12@gmail.com"]
edition = "2018"
license = "MIT"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexplay = "*"
hex = "0.3.2"
structopt = "0.2"
regex = "1.1.7"
crossbeam-utils = "0.6"
log = "0.4.6"
env_logger = "0.6.1"
pbr = "1.0.1"

[dependencies.pnet]
version = "0.22.0"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'